Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0a3c3a20c09d6f377 #Specific Amazon Machine Image ID
      InstanceType: t2.micro #t2 mircro instance which determines the hardware of the host computer used for your instance
