Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailbilityZone: us-east-1
      ImageId: ami-0cd40892ebca97aee #Specific Amazon Machine Image ID
      InstanceType: t2.micro #t2 mircro instance which determines the hardware of the host computer used for your instance
