Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0bdc4f385c18a557c #Specific Amazon Machine Image ID
      InstanceType: t2.micro #t2 mircro instance which determines the hardware of the host computer used for your instance
